# BilibiliVideoPro Configuration
# 一键三联奖励配置
triple_action_rewards:
  enabled: true
  
  # 默认奖励配置 (当BV号没有特定配置时使用)
  default:
    enabled: true
    reward_script: |
      tell *"&a恭喜！您已完成一键三联！"
      give diamond 1
      sound ENTITY_EXPERIENCE_ORB_PICKUP 1 1
  
  # 特定BV号的奖励配置
  specific_videos:
    # 示例配置1 - 高价值奖励
    "BV1234567890":
      enabled: true
      reward_script: |
        tell *"&6&l恭喜完成特殊视频的一键三联！"
        tell *"&e获得特殊奖励！"
        give diamond 5
        give emerald 3
        sound ENTITY_PLAYER_LEVELUP 1 1
        
    # 示例配置2 - 经验奖励
    "BV0987654321":
      enabled: true
      reward_script: |
        tell *"&b恭喜完成教程视频的一键三联！"
        tell *"&7获得经验奖励！"
        give experience 100
        sound ENTITY_EXPERIENCE_ORB_PICKUP 1 2
        
    # 示例配置3 - 金币奖励
    "BV1111111111":
      enabled: true
      reward_script: |
        tell *"&e恭喜完成活动视频的一键三联！"
        tell *"&6获得金币奖励！"
        give gold_ingot 10
        sound BLOCK_ANVIL_USE 1 1
        
    # 示例配置4 - 禁用奖励
    "BV2222222222":
      enabled: false
      reward_script: |
        tell *"&c此视频暂不提供奖励"

  # 冷却时间设置 (秒)
  cooldown:
    enabled: true
    # 每个BV号的冷却时间
    per_video: 3600  # 1小时
    # 每个玩家的全局冷却时间
    global: 300      # 5分钟

# 登录配置
login:
  # QR码过期时间 (秒)
  qr_expire_time: 180
  # 登录检查间隔 (毫秒)
  check_interval: 2000
  # 最大检查次数
  max_check_attempts: 90

# 一键三联检查配置
triple_check:
  # 检查超时时间 (秒)
  timeout: 30
  # 重试次数
  max_retries: 3
  # 重试间隔 (毫秒)
  retry_interval: 1000

# 调试配置
debug:
  enabled: false
  log_api_requests: false
  log_database_queries: false