# BilibiliVideoPro 插件配置文件
# Bilibili视频三连奖励插件 v1.0.0

# ===========================================
# 数据库配置
# ===========================================
database:
  # 数据库类型: sqlite 或 mysql
  type: sqlite
  
  # SQLite配置（当type=sqlite时使用）
  sqlite:
    # 数据库文件路径
    file: "plugins/BilibiliVideoPro/data.db"
  
  # MySQL配置（当type=mysql时使用）
  mysql:
    # 主机地址
    host: "localhost"
    # 端口号
    port: 3306
    # 数据库名
    database: "bilibili_video_pro"
    # 用户名
    username: "root"
    # 密码
    password: "password"
  
  # 连接池配置
  pool:
    # 最大连接池大小
    maxPoolSize: 10
    # 最小空闲连接数
    minIdle: 2
    # 连接最大生命周期（毫秒）
    maxLifetime: 600000
    # 连接超时时间（毫秒）
    connectionTimeout: 30000
    # 空闲超时时间（毫秒）
    idleTimeout: 300000
    # 验证超时时间（毫秒）
    validationTimeout: 5000

# ===========================================
# Bilibili API配置
# ===========================================
api:
  # Bilibili登录Cookie（用于API认证）
  # 获取方法：
  # 1. 登录bilibili.com
  # 2. 按F12打开开发者工具
  # 3. 在Network标签中找到任意请求
  # 4. 复制请求头中的Cookie值
  cookies:
    - "SESSDATA=your_sessdata_here"
    - "bili_jct=your_bili_jct_here"
    - "DedeUserID=your_userid_here"
  
  # API请求超时时间（秒）
  timeout: 30
  
  # 最大重试次数
  maxRetries: 3
  
  # 是否启用API请求日志
  enableLogging: false
  
  # API请求间隔（毫秒，防止被限流）
  requestInterval: 1000

# ===========================================
# 奖励配置
# ===========================================
rewards:
  # 是否启用奖励系统
  enabled: true
  
  # 绑定奖励
  bind:
    enabled: true
    commands:
      - "give {player} diamond 5"
      - "tellraw {player} {\"text\":\"感谢绑定Bilibili账号！获得5颗钻石奖励\",\"color\":\"green\"}"
  
  # 点赞奖励
  like:
    enabled: true
    commands:
      - "give {player} gold_ingot 2"
      - "tellraw {player} {\"text\":\"感谢点赞视频！获得2个金锭奖励\",\"color\":\"yellow\"}"
  
  # 投币奖励
  coin:
    enabled: true
    # 每投一枚硬币的奖励
    commands:
      - "give {player} iron_ingot 3"
      - "tellraw {player} {\"text\":\"感谢投币支持！获得3个铁锭奖励\",\"color\":\"gray\"}"
  
  # 收藏奖励
  favorite:
    enabled: true
    commands:
      - "give {player} emerald 1"
      - "tellraw {player} {\"text\":\"感谢收藏视频！获得1个绿宝石奖励\",\"color\":\"aqua\"}"
  
  # 完整三连奖励（点赞+投币+收藏）
  fullTriple:
    enabled: true
    commands:
      - "give {player} diamond 10"
      - "give {player} emerald_block 1"
      - "tellraw {player} {\"text\":\"恭喜完成三连！获得丰厚奖励\",\"color\":\"gold\"}"
      - "broadcast {player} 完成了视频三连，获得了特殊奖励！"

# ===========================================
# 检测配置
# ===========================================
detection:
  # 是否启用自动检测
  enabled: true
  
  # 检测间隔（秒）
  interval: 300
  
  # 检测的UP主列表（留空表示检测所有绑定用户关注的UP主）
  targetUploaders: [ ]
  
  # 是否只检测最新视频
  onlyLatestVideos: true
  
  # 最新视频的时间范围（小时）
  latestVideoHours: 24

# ===========================================
# 消息配置
# ===========================================
messages:
  # 命令反馈消息的语言
  language: "zh_CN"
  
  # 是否启用广播消息
  broadcast:
    enabled: true
    # 三连成功时的广播
    tripleSuccess: "§6{player} §a对视频 §e{title} §a完成了三连操作！"

# ===========================================
# 高级配置
# ===========================================
advanced:
  # 数据同步间隔（分钟）
  syncInterval: 30
  
  # 是否启用数据库自动备份（仅SQLite）
  autoBackup:
    enabled: true
    # 备份间隔（小时）
    interval: 24
    # 保留备份数量
    keepCount: 7
  
  # 性能优化
  performance:
    # 是否启用缓存
    cacheEnabled: true
    # 缓存过期时间（分钟）
    cacheExpiration: 10 