name: Build

on:
  push:
    branches:
      - master  # 根据你的主分支名称修改

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '#build')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache build outputs
        uses: actions/cache@v4
        with:
          path: |
            build
            .gradle
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Clean and build
        run: ./gradlew clean build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/libs/
          retention-days: 7  # 添加保留天数，避免长期占用存储空间